//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzychodniaPOZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacjent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacjent()
        {
            this.WizytaBadanie = new HashSet<WizytaBadanie>();
            this.WizytaLekarz = new HashSet<WizytaLekarz>();
        }
    
        public int PacjentId { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Pesel { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
        public string ConfirmHaslo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WizytaBadanie> WizytaBadanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WizytaLekarz> WizytaLekarz { get; set; }
    }
}
